language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: rqnEninAmFqCXxSGULSiBui7tXRys1ZnaWFTJX5ST7lPGMR/+obzrCilj+woCMw+2sOn8Buyobdyudu19lB8L0OsyiIzP4pMF9XZ4OET4YwoCH4z9HrS9ykAKRwdStDccbBlpnm6J7JcXs0rRtMqoLBgamqfCep4ESRNtCAngS0U3O6LPsjEH9r876XyrfD/kwbEU49O3vqVuBhGXYZhgW9qGZBKQvvBy+9lJpskF8YddWe6pyLm+jpN8ARwpCMEePytPJy7UwQ06PPgqPhcEVyJ+HF1DxjHiWxXZA9a3zt7kxaAGWKLd0UdqBgsSAPV8KoF9oEoVluJpFkuENT82FST7ZGkDkpE8PV5jXZLKdaDnZA+k5do4fkjRbuGOO5PC0Jd7y4n4VarwJOXaXbrSs9d1420fK9FclbXTRUb2UEeUY3vnovyChHvnr6pRBD49OkZdd8gJsOrQovBJJANOjUdhvkWBWzY3+Zt+qDCsMZit1ymIW6wuQNIn/t98ryojPJb6clZaefGCPR5HkSwVIDqKWdXhDSzlsD6WD6hOIbcSLOu38NSrAB5uzLacQ4rUBOD515gM1kwCYr+kE2MJXvIg1eTllKecldc7oiSo52JraJjjpb3kEI3SOSbRcHMTjFb2gCWLkFX0U6MAlRK3rTI+cJBk/qI6lRBogxRk40=
  app: serene-river-83063
  on:
    repo: KLlorente/gym-hopper
